# Generated by Django 5.2.14 on 2026-05-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadershiphistory',
            options={'managed': False, 'ordering': ['-start_date'], 'verbose_name_plural': 'Leadership Histories'},
        ),
    ]
