# Generated by Django 5.0 on 2026-04-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_remove_church_church_code_church_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('offering_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('pledge', 'Pledge'), ('building', 'Building Fund'), ('mission', 'Mission Fund'), ('benevolence', 'Benevolence'), ('thanksgiving', 'Thanksgiving'), ('other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='churches.church')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_offerings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offerings',
                'ordering': ['-payment_date'],
            },
        ),
    ]
