# Generated by Django 5.2.14 on 2026-05-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offerings", "0002_offering_payment_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offering",
            options={"managed": False, "ordering": ["-payment_date"]},
        ),
    ]
