# Generated by Django 5.0 on 2026-04-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('church_code', models.CharField(max_length=50, unique=True)),
                ('church_type', models.CharField(choices=[('national', 'National'), ('zone', 'Zone'), ('region', 'Region'), ('district', 'District'), ('local', 'Local')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church_logos/')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
            ],
            options={
                'db_table': 'churches',
                'ordering': ['church_type', 'name'],
            },
        ),
    ]
