# Generated by Django 5.0 on 2026-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='church_code',
        ),
        migrations.AddField(
            model_name='church',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
