# Generated by Django 5.0 on 2026-04-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_remove_church_church_code_church_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('churches.church',),
        ),
        migrations.CreateModel(
            name='LocalChurch',
            fields=[
            ],
            options={
                'verbose_name': 'Local Church',
                'verbose_name_plural': 'Local Churches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('churches.church',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('churches.church',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('churches.church',),
        ),
    ]
