# Generated by Django 5.2.14 on 2026-05-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0006_churchpaymentdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localchurch',
            options={'verbose_name': 'Church', 'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterField(
            model_name='church',
            name='church_type',
            field=models.CharField(choices=[('national', 'National'), ('zone', 'Zone'), ('region', 'Region'), ('district', 'District'), ('local', 'Church')], max_length=50),
        ),
    ]
