# Generated by Django 5.0 on 2026-04-06 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_remove_church_church_code_church_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('service', 'Service'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('prayer_meeting', 'Prayer Meeting'), ('youth', 'Youth Event'), ('children', 'Children Event'), ('outreach', 'Outreach'), ('other', 'Other')], default='service', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True)),
                ('organizer_name', models.CharField(blank=True, max_length=255)),
                ('organizer_contact', models.CharField(blank=True, max_length=100)),
                ('is_popup_news', models.BooleanField(default=False)),
                ('popup_start_date', models.DateTimeField(blank=True, null=True)),
                ('popup_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='churches.church')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-start_date'],
            },
        ),
    ]
