# Generated by Django 5.2.14 on 2026-05-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ['-start_date']},
        ),
    ]
