# Generated by Django 5.0 on 2026-04-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prayed', 'Prayed'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('answer_notes', models.TextField(blank=True)),
                ('prayer_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
