# Generated by Django 5.2.14 on 2026-05-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_two_factor_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("national_leader", "National Leader"),
                    ("zone_leader", "Zone Leader"),
                    ("regional_leader", "Regional Leader"),
                    ("district_leader", "District Leader"),
                    ("local_leader", "Church Leader"),
                    ("local_member", "Church Member"),
                    ("finance_team", "Finance Team"),
                ],
                default="local_member",
                max_length=50,
            ),
        ),
    ]
