# Generated by Django 5.0 on 2026-04-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_remove_church_church_code_church_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_reason', models.TextField()),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='transfer_letters/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_from_transfers', to=settings.AUTH_USER_MODEL)),
                ('approved_by_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_to_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='churches.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('to_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='churches.church')),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
